# Generated by Django 3.1.1 on 2023-09-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_studentclub_studentsclub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsClub',
        ),
    ]
